require("jay.plugins-setup")

require("jay.core.options")
require("jay.core.keymaps")
require("jay.core.colorscheme")

require("jay.plugins.comment")
require("jay.plugins.nvim-tree")
require("jay.plugins.lualine")
require("jay.plugins.telescope")
require("jay.plugins.nvim-cmp")
require("jay.plugins.lsp.mason")
-- require("jay.plugins.lsp.lspsaga")
require("jay.plugins.lsp.lspconfig")
require("jay.plugins.lsp.null-ls")
require("jay.plugins.autopairs")
require("jay.plugins.treesitter")
require("jay.plugins.gitsigns")
